### PR TITLE
feat(java 21): complete pattern matching for switch statements

### PR DESCRIPTION
**Pull request by brandonspark**
## What:
This PR adds in the last thing for supporting pattern matching for `switch` statements, as in Java 21, namely guards.

## Why:
We should support the features of Java 21.

## How:
Just added a `guard` nonterminal and put it in the right place, and added more tests for other Java 21 `switch` features.

## Test plan:
`tree-sitter test`

Checklist:
- [ ] All tests pass in CI.
- [X] There are sufficient tests for the new fix/feature.
- [X] Grammar rules have not been renamed unless absolutely necessary.
- [X] The conflicts section hasn't grown too much.
- [X] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
need to rebase

**Comment by brandonspark** [comment]
@aryx rebased now

**Comment by amaanq** [comment]
Can you remove the regenerated files? Then it'd be nice to merge your 3 PRs and *then* generate after that

**Comment by brandonspark** [comment]
@amaanq done

**Comment by brandonspark** [comment]
@amaanq well, this will also fail CI in the interim, unfortunately...

**Review by aryx — APPROVED** [review]

**Comment by brandonspark** [comment]
@amaanq it seems it's not possible to do "partial commits" with the regeneration step at a later time, because CI must pass before i merge. i think i'm just going to merge individually.

**Comment by amaanq** [comment]
okay, that's fine. you can add back the generated files.

**Comment by brandonspark** [comment]
@aryx could you merge this?

**Pull request merged**
