### PR TITLE
Update to example repositories and to the grammar to support new cases

### PR DESCRIPTION
**Pull request by bmahe**
Example repositories updated:
* Update guava to 31.1
* Update RxJava to 3.1.5
 
Added new example repositories:
* Apache Flink
* Apache Log4j2
* Apache Cassandra

 
The grammar has been updated to address the following cases:
* Add support for annotations in array creation  
* Reserved identifiers used as a lambda parameter
* Enum declared inside an annotation
* Conflict between switch as a statement or an expression when used in
   the following pattern:
    ```java
    switch(foo) {
      ...
    }
    ++bar;
    ```

Checklist:
- [X] All tests pass in CI.
- [X] There are sufficient tests for the new fix/feature.
- [X] Grammar rules have not been renamed unless absolutely necessary.
- [X] The conflicts section hasn't grown too much.
- [X] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by mjambon** [comment]
Looks good to me. Can we merge this? (I'm not merging because I'm not the usual reviewer on this repo)

**Comment by bmahe** [comment]
Hi!
Anything I can do to help with this PR?

**Comment by bmahe** [comment]
I updated this PR based on #117 and resolved the conflicts.

Tests and parse-examples pass locally:
```bash
Successfully parsed 29308 of 29311 example files (100.0%)
```

**Comment by aryx** [comment]
Looks good!

**Review by aryx — APPROVED** [review]

**Pull request merged**
