### PR TITLE
Add an alias to method invocation to differentiate between method name and field property

### LINKED ISSUE #45: Limitations of scoped_identifier or any other recursive rules
### Problem description

I am working on tree-sitter support for language-java and am encountering multiple limitations related to [scoped_identifier](https://github.com/tree-sitter/tree-sitter-java/blob/master/grammar.js#L771) rule being recursive and the fact that only the immediate child combinator is supported in tree-sitter grammar (https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#syntax-highlighting), e.g. I don't know how to account for such recursion when trying to scope `marker_annotation` (see code below).

I figured I could do something like this:
```cson
'''
marker_annotation > identifier,
marker_annotation > scoped_identifier
''': 'scope'
```

But this does not allow me to highlight individual identifiers and would include some other nodes like `.`.

Would appreciate if someone could explain the idea behind `scoped_identifier` and suggest any possible workarounds or fixes, e.g. replacing `scoped_identifier` with a sequence of `identifier`s instead. Thanks!

This actually relates to PR #44, where I do just that.

### Actual parse tree output (optional)

```java
@Annotation.Option
public class B {
  // do something
}

// (program [0, 0] - [5, 0]
//   (class_declaration [0, 0] - [3, 1]
//     (modifier [0, 0] - [0, 18]
//       (marker_annotation [0, 0] - [0, 18]
//         (scoped_identifier [0, 1] - [0, 18]
//           (identifier [0, 1] - [0, 11])
//           (identifier [0, 12] - [0, 18]))))
//     (modifier [1, 0] - [1, 6])
//     (identifier [1, 13] - [1, 14])
//     (class_body [1, 15] - [3, 1]
//       (comment [2, 2] - [2, 17]))))

@Annotation.Option.Option2
public class C {
  // do something
}

// (program [0, 0] - [5, 0]
//   (class_declaration [0, 0] - [3, 1]
//     (modifier [0, 0] - [0, 26]
//       (marker_annotation [0, 0] - [0, 26]
//         (scoped_identifier [0, 1] - [0, 26]
//           (scoped_identifier [0, 1] - [0, 18]
//             (identifier [0, 1] - [0, 11])
//             (identifier [0, 12] - [0, 18]))
//           (identifier [0, 19] - [0, 26]))))
//     (modifier [1, 0] - [1, 6])
//     (identifier [1, 13] - [1, 14])
//     (class_body [1, 15] - [3, 1]
//       (comment [2, 2] - [2, 17]))))
```

### PR DESCRIPTION
**Pull request by sadikovi**
When working on language-java grammar, I found that it is difficult to distinguish between the following cases using tree-sitter-java generated tree:

```
call();
obj.call();
obj.prop.call();
```

which translates to the following:

```
(expression_statement (method_invocation (identifier) (argument_list)))
(expression_statement (method_invocation (identifier) (identifier) (argument_list)))
(expression_statement (method_invocation (field_access (identifier) (identifier)) (identifier) (argument_list)))
```

For example, it is difficult to differentiate between the method name and property, i.e. programmatically select the last identifier in a sequence (https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#advanced-selectors). I could hard-code the second case but that breaks the first and third cases.

This PR proposes to introduce an alias on `primary_expression` to ensure that we can always extract method name. For example, with this change the second case would look like this:

```
(method_invocation (primary (identifier)) (identifier) (argument_list)))
```

I added a unit test for method invocations and updated the existing tests to include `primary` alias.

However, this is a breaking change. The drawbacks are:
- The generated tree will include an additional level for `primary` node (see the test).
- Due to the above, `this` and `super` are parsed differently. While the latter does not change, the former will be wrapped with `primary` (see the test).

Although I assume that some people might be relying on this behaviour, this change fixed the issue for me and did not result in any regressions.

Fixes #45

### CODE REVIEW

**Comment by sadikovi** [comment]
@maxbrunsfeld can you review? Thanks.

**Comment by sadikovi** [comment]
I thought about it and found that it might be a bit inconsistent, maybe we should wrap all of the `$.primary_expression` with an alias. Let me know what you think.

**Comment by sadikovi** [comment]
Can I get a review on this PR?

**Comment by maxbrunsfeld** [comment]
@sadikovi I don't think we want to add this `primary` rule. In general, when using this parser, you can use the *fields* ([`object`, `name`, `type_arguments`, `arguments`](https://github.com/tree-sitter/tree-sitter-java/blob/bd6186c24d5eb13b4623efac9d944dcc095c0dad/grammar.js#L326-L341)) to find a specific part of the `method_invocation`.

Unfortunately, Atom's highlighting system is too old to match on fields. I would ideally like for this parser to work well in Atom, but I don't think this extra node makes sense for other users of `tree-sitter-java`, and Atom support isn't our first priority, since this parser isn't built into Atom, and we're not actively developing new Tree-sitter related features in Atom.

**Comment by sadikovi** [comment]
I thought tree-sitter was built with a goal of providing robust language parsing system in Atom: https://github.blog/2018-10-31-atoms-new-parsing-system/. Although it has been a while, I did not know that Atom was not the first priority. My apologies! I should have never assumed that.

**Pull request closed without merging**
