### PR TITLE
Small improvements for records and instanceof

### PR DESCRIPTION
**Pull request by bmahe**
This adds support for
* Records declared as top level, with or without generics
* Pattern matching for instanceof. See [jep-394](https://openjdk.org/jeps/394)

Checklist:
- [ ] All tests pass in CI.
- [x] There are sufficient tests for the new fix/feature.
- [x] Grammar rules have not been renamed unless absolutely necessary.
- [ ] The conflicts section hasn't grown too much.
- [ ] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by aryx** [comment]
Looks great!

**Comment by aryx** [comment]
Not sure what's going on with the CI failure

**Comment by bmahe** [comment]
I verified the tests pass locally:


```
[bruno@buo tree-sitter-java]$ tree-sitter test
  comments:
    ✓ comment
    ✓ comments and literals
  precedence:
    ✓ Precedence
  types:
    ✓ integral types
    ✓ floating point types
  literals:
    ✓ decimal integer literals
    ✓ hex integer literals
    ✓ octal integer literals
    ✓ binary integer literal
    ✓ floating point literals
    ✓ boolean literals
    ✓ character literals
    ✓ string literals
    ✓ text block
    ✓ null literals
    ✓ char escapes
    ✓ octal escapes
    ✓ unicode escapes
    ✓ ascii escapes
  declarations:
    ✓ local variable
    ✓ local array variable
    ✓ module
    ✓ module with normal annotation
    ✓ module with marker annotation
    ✓ module with single element annotation
    ✓ package_declaration
    ✓ module directive
    ✓ module directive with requires, exports, opens, uses and provides
    ✓ single type import declaration
    ✓ type_import_on_declaraction
    ✓ single static import declaration
    ✓ static import on demand declaration
    ✓ class declaration
    ✓ class declaration involving public, private, abstract and superclass
    ✓ class declaration with implements
    ✓ class declaration with body
    ✓ interface declaration
    ✓ interface declaration with extends
    ✓ interface with annotation type declaration
    ✓ method declaration
    ✓ constructor declaration
    ✓ throws
    ✓ object instantiation
    ✓ variable declaration
    ✓ enum declaration
    ✓ record declaration
    ✓ record declaration with generics
    ✓ record declaration inside a class
    ✓ class declaration with dollar-sign identifiers
    ✓  Sealed classes
  expressions:
    ✓ standalone assignment expression
    ✓ standalone binary expression
    ✓ instanceof expressions
    ✓ if statements
    ✓ if statements with braces
    ✓ if statements with assignment without braces
    ✓ if then else statement
    ✓ nested if then else statements
    ✓ ternary expressions
    ✓ for statement
    ✓ Enhanced for statements
    ✓ while statement
    ✓ try-with-resources statements
    ✓ return statement
    ✓ annotation
    ✓ marker annotation
    ✓ single element annotation
    ✓ lambda expression
    ✓ traditional switch statement
    ✓ functional switch statement
    ✓ traditional-style switch expression
    ✓ functional switch expression
    ✓ switch expression with block
    ✓ switch expressions added
    ✓ type arguments
    ✓ wildcard
    ✓ type arguments with generic types
    ✓ empty type arguments
    ✓ method references
    ✓ Non-ascii identifiers
syntax highlighting:
  ✓ types.java (17 assertions)
```
[bruno@buo tree-sitter-java]$ ./script/parse-examples
Warning: You have not configured any parser directories!
Please run `tree-sitter init-config` and edit the resulting
configuration file to indicate where we should look for
language grammars.

Successfully parsed 10738 of 10738 example files (100.0%)
```

**Comment by mjambon** [comment]
Looks good to me. Can we merge this?

**Comment by bmahe** [comment]
Hi!
Anything I can do to help with this PR?

**Comment by maxbrunsfeld** [comment]
Thanks for following up with that fix @bmahe.

**Comment by bmahe** [comment]
Fantastic! Thank you so much!

**Pull request merged**
