### PR TITLE
0.20

### PR DESCRIPTION
**Pull request by Luni-4**
Checklist:
- [x] All tests pass in CI.
- [ ] There are sufficient tests for the new fix/feature.
- [ ] Grammar rules have not been renamed unless absolutely necessary.
- [ ] The conflicts section hasn't grown too much.
- [ ] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

This PR updates `tree-sitter-java` to 0.20

@maxbrunsfeld 

Can we release it on crates.io also? Thanks in advance! :)

### CODE REVIEW

**Review by aryx — APPROVED** [review]
lgtm

**Comment by edg-l** [comment]
bump

**Comment by hahnbeelee** [comment]
bump

**Comment by aryx** [comment]
@maxbrunsfeld not sure what's going on again here. The CI jobs seem blocked.

**Review by aryx — APPROVED** [review]

**Comment by Luni-4** [comment]
Closed due to https://github.com/tree-sitter/tree-sitter-java/releases/tag/v0.20.0

**Pull request closed without merging**
