### PR TITLE
Fix continuous integration builds

### LINKED ISSUE #47: Fix continuous integration build
### Problem description

https://github.com/tree-sitter/tree-sitter-java/pull/44 is failing but the error seems unrelated to the PR.

Screen Shot 2019-06-28 at 23 04 44

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #47 by uplifting continuous integration build configuration to other tree-sitter libraries.

I saw #44 failed with 'npm ci'. Updating dependency versions to catch up with other repositories (tree-sitter-ruby)
 
- Upgrading Node.js from 8 to 11. Node.js 11 worked good for tree-sitter-javascript 2 months ago ([tree-sitter-javascript travis ci](https://travis-ci.org/tree-sitter/tree-sitter-javascript/builds/523425335?utm_source=github_status&utm_medium=notification)).
- New tree-sitter-cli solves build problem in Windows (Appveyor) x64.
  - (Node.js 11, tree-sitter-cli 0.13.1, Appveyor x64) => [failed](https://ci.appveyor.com/project/maxbrunsfeld/tree-sitter-java/builds/25628725) 
  - (Node.js 10, tree-sitter-cli 0.13.1, Appveyor x64) => [failed](https://ci.appveyor.com/project/maxbrunsfeld/tree-sitter-java/builds/25628767) 
  - (Node.js 10, tree-sitter-cli 0.15.3, Appveyor x64) => [succeeded](https://ci.appveyor.com/project/maxbrunsfeld/tree-sitter-java/builds/25628789) 
  - (Node.js 11, tree-sitter-cli 0.15.3, Appveyor x64) => [succeeded](https://ci.appveyor.com/project/maxbrunsfeld/tree-sitter-java/builds/25628846)
- Removed `package-lock.json` because this prevents updating versions in package.json. Other repositories (tree-sitter-ruby, tree-sitter-python, etc.) don't have this file.
- upgraded version of nan to 2.12.1 to avoid the error `Invalid Version: https://registry.npmjs.org/nan/-/nan-2.8.0.tgz`.
- Added Appveyor platform x86 to match [tree-sitter-ruby's configuration](https://github.com/tree-sitter/tree-sitter-ruby/blob/master/.appveyor.yml#L8).

# For Repository Owners

Would you also update the required status check of Appveyor? (branch => pr)
https://help.github.com/en/articles/about-required-status-checks

### CODE REVIEW

**Comment by suztomo** [comment]
@rewinfrey @aymannadeem Would you take a look? (I picked up your names from https://github.com/tree-sitter/tree-sitter-java/pull/39#issuecomment-457736793)

**Comment by suztomo** [comment]
@maxbrunsfeld I see you’re assigned as reviewer. Would you take a look?

BTW [your talk at Strangeloop on Youtube](https://youtu.be/Jes3bD6P0To) was very inspiring!

**Comment by maxbrunsfeld** [comment]
> BTW your talk at Strangeloop on Youtube was very inspiring!

Thanks!

> Would you also update the required status check of Appveyor?

Thanks for pointing that out. I updated it.

**Comment by suztomo** [comment]
@maxbrunsfeld I see you’re assigned as reviewer. Would you take a look?

BTW [your talk at Strangeloop on Youtube](https://youtu.be/Jes3bD6P0To) was very inspiring!

**Pull request merged**
