### PR TITLE
Update package_declaration to use identifiers and add method_name

### PR DESCRIPTION
**Pull request by sadikovi**
This PR updates:
- `package_declaration`, instead of using `scoped_identifier`, I figured it would be better to just use a sequence of identifiers similar to import_declaration.
- `method_invocation`, I added `method_name` rule to extract method name with attributes, otherwise, it is impossible to scope method name in language-java.

I added a test for `package_declaration` and updated tests for `method_invocation`.

### CODE REVIEW

**Comment by sadikovi** [comment]
The build failed with `npm ERR! Invalid Version: https://registry.npmjs.org/nan/-/nan-2.8.0.tgz`, does not seem to be related. @aymannadeem could you take a look? Thank you!

**Comment by sadikovi** [comment]
ping @Aerijo and @50Wliu, could you take a look at the PR and help me with build? Thanks!

**Comment by suztomo** [comment]
With #46 merged to master, the continuous integration should succeed now. Would you merge master?

**Comment by sadikovi** [comment]
@suztomo rebased, thanks!

**Comment by sadikovi** [comment]
@maxbrunsfeld can you review? Thanks.

**Comment by maxbrunsfeld** [comment]
Hey @sadikovi - I see your point about the difficulties of highlighting things within `scoped_identifier`. I will review this when I get a chance.

**Comment by sadikovi** [comment]
Thank you.

I will rebase tonight, looks like a lot of changes have been made here. Actually, this changes are only to have some means to extract method name (just wraps the last identifier and argument list into a `method_name` rule) and make `package` rule to be similar to `import` rule (just a sequence of identifiers).

**Pull request closed without merging**
