### PR TITLE
fix, Local variable declaration with generic types and scoped type id…

### LINKED ISSUE #138: Variable declaration with scoped generic type parsed as binary expression
### Problem description

The variable declaration `util.List<X> x = null;` gets parsed as nested binary expressions with operators `<`, `>` and `=`, but it should be a "local variable declaration".
This worked with v0.20.0 but does not anymore with v0.20.1. Also, it works if the type is not scoped, e.g. `List<x> x = null;`.

```java
class X {
	void foo() {
    	util.List<X> x = null;
    }
}
```

### PR DESCRIPTION
**Pull request by ahumenberger**
This change partially reverts a change from #125 which caused the regression. The test case introduced by #125 still exists and works.

Fixes #138

@danzat Was there a specific reason for this particular change? If yes, then a test case is missing.

Checklist:
- [ ] All tests pass in CI.
- [ ] There are sufficient tests for the new fix/feature.
- [ ] Grammar rules have not been renamed unless absolutely necessary.
- [ ] The conflicts section hasn't grown too much.
- [ ] The parser size hasn't grown too much (check the value of STATE_COUNT in src/parser.c).

### CODE REVIEW

**Comment by danzat** [comment]
Well, I think I couldn't get the precedence to work without the "dynamic", but apparently I was wrong.

If the test does indeed pass then I have no objection to this change.

**Review by aryx — APPROVED** [review]
thx for fixing that!

**Comment by aryx** [comment]
can you rebase?

**Comment by ahumenberger** [comment]
> can you rebase?

Yes, but there seems to be a problem with the grammar on master now: #141

**Review by aryx — APPROVED** [review]

**Comment by amaanq** [comment]
Seems that you merged them in the wrong way @aryx

**Pull request merged**
