### PR TITLE
Restructure modifier rules

### LINKED ISSUE #38: Parse accessibility separately from `modifier`
When we parse the following Java file:

```java
public class Example {

    public void example() { }
    
}
```

We identify `public` as `modifier`. It's possible from the position of `modifier` in the parse tree for the consumer to selectively inspect the contents, but `modifier` in the `tree-sitter-java` grammar could mean other things (e.g. `abstract`, `native`, `sychronized`, etc.) that aren't directly accessibility related.

What about treating accessibility (i.e. `public`, `protected`, and `private`) in the Java grammar as first class nodes in the parse tree?

### Suggested diff

```diff
(program [0, 0] - [5, 0]
  (class_declaration [0, 0] - [4, 1]
-- (modifier [0, 0] - [0, 6])
++ (public [0, 0] - [0, 6])
    (identifier [0, 13] - [0, 20])
    (class_body [0, 21] - [4, 1]
      (method_declaration [2, 4] - [2, 29]
--      (modifier [2, 4] - [2, 10])
++      (public [2,4] - [2,10])
        (method_header [2, 11] - [2, 25]
          (void_type [2, 11] - [2, 15])
          (method_declarator [2, 16] - [2, 25]
            (identifier [2, 16] - [2, 23])))
        (method_body [2, 26] - [2, 29]
          (block [2, 26] - [2, 29]))))))
```

### PR DESCRIPTION
**Pull request by rewinfrey**
Fixes #38 by adding an `accessibility_modifier` production to the grammar. This mirrors the approach in the [`tree-sitter-typescript`](https://github.com/tree-sitter/tree-sitter-typescript/blob/47d3013a6d2aaad54bd31b1465073429b4b72cfb/grammar.js#L388-L392) grammar for consistency.

Given the Java code:

```java
public class Example {

    public void example() { }
    
}
```

`tree-sitter parse` generates:

```shell
(program [0, 0] - [5, 0]
  (class_declaration [0, 0] - [4, 1]
    (modifier [0, 0] - [0, 6]
      (accessibility_modifier [0, 0] - [0, 6]))
    (identifier [0, 13] - [0, 20])
    (class_body [0, 21] - [4, 1]
      (method_declaration [2, 4] - [2, 29]
        (modifier [2, 4] - [2, 10]
          (accessibility_modifier [2, 4] - [2, 10]))
        (method_header [2, 11] - [2, 25]
          (void_type [2, 11] - [2, 15])
          (method_declarator [2, 16] - [2, 25]
            (identifier [2, 16] - [2, 23])))
        (method_body [2, 26] - [2, 29]
          (block [2, 26] - [2, 29]))))))
```

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
It seems a bit odd to me to have `public` be a child of `accessibility_modifier`, which is itself a child of `modifier`. It's true that `tree-sitter-typescript` has an `accessibility_modifier` rule, but that's because in TypeScript, there are no other types of modifiers; there are just accessibility modifiers.

Does breaking out `accessibility_modifier` from `modifier` make it easier to consume the syntax tree? I would think that either way, you'd have to look inside of that node to find out if it's `public`, `private`, or `protected`, just like you would have to look inside of a `modifier`.

**Comment by rewinfrey** [comment]
> Does breaking out `accessibility_modifier` from `modifier` make it easier to consume the syntax tree?

@maxbrunsfeld I think so. Having fewer named nodes to alternate between when descending into the `modifier` subtree reduces the search space. Fewer children to search through reduces the worst case number of backtracking operations we'd need to perform. So if my program can attempt to match and fail against 1 child (`accessibility_modifier`) that saves my program from needing to attempt to match and fail against 3 children (i.e. `public`, `protected`, `private`). I'd be happy to show you in my specific context what I mean if you want to 🍐.

Is there a reason you don't want a node increasing specificity? In its current state the `modifier` production contains many things right now. I thought that improving specificity of nodes would also improve readability of the tree for humans, something I think is also 👍 . Curious if there are concerns or problems with this for other contexts that I'm not aware of?

> Basically, in the grammar we'd have:
> 
> ```js
> modifiers: $ => repeat1(choice(
>   $._annotation,
>   'public',
>   // ...
> )),
> 
> method_declaration: $ => seq(
>   optional($.modifiers),
>   $.method_header,
>   // ...
> )
> ```

I had originally thought about this too, but opted to keep the patch as minimal as possible. I really like this approach 👍But...trying to implement this in https://github.com/tree-sitter/tree-sitter-java/pull/39/commits/d7e71a62334b1776ad166b1b188bfb634dfa6f29, I'm unable to generate the parser:

```sh
Error: Unresolved conflict for symbol sequence:

  _annotation  •  '@'  …

Possible interpretations:

  1:  (wildcard_repeat1  _annotation)  •  '@'  …
  2:  (modifiers_repeat1  _annotation)  •  '@'  …

Possible resolutions:

  1:  Add a conflict for these rules:

```

I could use some help with this error 😅

**Comment by aymannadeem** [comment]
Readability, alignment with Typescript grammar and increasing specificity are all good reasons to make this change! Thanks for taking this on, @rewinfrey!

I don't have strong opinions either way because I don't know what the magnitude of the benefit here is on downstream output (as in, I do think accessibility information is valuable in potential analyses—but do we have any clarity on what analyses this would drastically move forward right now?). I trust you and @maxbrunsfeld to net out on a sensible solution, but curious if the language spec makes a distinction (I know I consolidated a lot of constructs into simpler, coarser categories sometimes). 

Happy to help look at and work through the error later once I have a bit more bandwidth. 😄

**Comment by rewinfrey** [comment]
@aymannadeem, @maxbrunsfeld and I 🍐 on this and helped me understand some bits that are good to pass on.

Allocating extra nodes in the tree increases memory usage and involves a little extra work for traversing the tree. By keeping the access control modifiers within a single `modifiers` node, we can prevent a bunch of extra nodes from being created when parsing Java files. This is particularly useful here, because access modifiers are a common syntax used in most declarations. It might not be as immediately readable in terms of understanding what modifiers there are, but if we need to make that clearer we can. For our needs though, this doesn't pose a problem.

@maxbrunsfeld and I also used the new Rust `tree-sitter-cli` which was 🤘 to generate this parser. Even though running the parser now shouldn't pose any problems with `node-tree-sitter`, it's probably safer to wait until the new Rust cli merges before we merge this.

**Comment by aymannadeem** [comment]
Right on! And word, learned about impact of increasing nodes on memory footprint while talking to  @maxbrunsfeld separately about the `ref` additions to grammars.

**Comment by maxbrunsfeld** [comment]
> I also used the new Rust `tree-sitter-cli` which was 🤘 to generate this parser.

Just to add onto that: we used the new CLI because the old CLI had some bugs in reporting conflicts which made it impossible to use `conflicts` to fix the error. Those bugs have been fixed in the new CLI.

**Comment by rewinfrey** [comment]
There's two problems in CI currently:

Using the new Rust CLI, there appears to be a configuration problem for TravisCI when we invoke `tree-sitter parse` within `script/parse-examples`.

If we switch back to using the latest tree-sitter-cli before Rust (v0.13.16), AppVeyor reports the following error:
`error MSB8013: This project doesn't contain the Configuration and Platform combination of Release|Win32. [C:\projects\tree-sitter-java\node_modules\tree-sitter-cli\build\vendor\tree-sitter\compiler.vcxproj]`

Going to wait for the Rust CLI to land and then merge this branch into master. That prevents spending unnecessary time on the AppVeyor error. The process of updating tree-sitter language repos to the new Rust CLI will be a forcing function for solving the TravisCI configuration problem.

**Comment by aymannadeem** [comment]
@rewinfrey does running that script work fine locally or does it fail there too?

**Comment by rewinfrey** [comment]
@aymannadeem running `npm test` which also invokes `script/parse-examples` locally is 👍 for both tree-sitter-cli v.0.13.16 and the new Rust CLI.

**Pull request merged**
