### PR TITLE
configure rules precedence according to the spec

### PR DESCRIPTION
**Pull request by kamadorueda**
- The Java engine evaluates some expressions first according
  to precedence rules
- This commit configures the grammar according to the spec
- Add comments
- Make node-gyp rebuild so it does not break the second time
  you run it
- This solves two issues reported so far, but they may be
  others not yet exposed in real life:
  - https://github.com/tree-sitter/tree-sitter-java/issues/68
  - https://github.com/tree-sitter/tree-sitter-java/issues/70
- Add tests for solved issues

### CODE REVIEW

**Comment by kamadorueda** [comment]
@aryx

**Comment by aryx** [comment]
Fantastic!

**Comment by aryx** [comment]
@dcreager or @maxbrunsfeld who would be good to review and merge this?

**Comment by maxbrunsfeld** [comment]
Could you add tests (or modify one or more existing tests) for those two issues that you mentioned, that this PR fixes?

**Comment by kamadorueda** [comment]
@maxbrunsfeld, I just added some _precedence_ tests, these are the outputs of running the CI locally:

`$ npm run-script build`

```
> tree-sitter-java@0.19.1 build /home/kamado/Documents/github/kamadorueda/tree-sitter-java
> tree-sitter generate && node-gyp rebuild

make: Entering directory '/home/kamado/Documents/github/kamadorueda/tree-sitter-java/build'
  CC(target) Release/obj.target/tree_sitter_java_binding/src/parser.o
In file included from ../src/parser.c:1:
../src/parser.c: In function 'ts_lex_keywords':
../src/tree_sitter/parser.h:135:8: warning: variable 'eof' set but not used [-Wunused-but-set-variable]
  135 |   bool eof = false;             \
      |        ^~~
../src/parser.c:5269:3: note: in expansion of macro 'START_LEXER'
 5269 |   START_LEXER();
      |   ^~~~~~~~~~~
  CXX(target) Release/obj.target/tree_sitter_java_binding/bindings/node/binding.o
In file included from ../bindings/node/binding.cc:2:
/home/kamado/.cache/node-gyp/14.15.4/include/node/node.h:758:7: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kamado/.cache/node-gyp/14.15.4/include/node/node.h:792:3: note: in expansion of macro 'NODE_MODULE_X'
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../bindings/node/binding.cc:26:1: note: in expansion of macro 'NODE_MODULE'
   26 | NODE_MODULE(tree_sitter_java_binding, Init)
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/tree_sitter_java_binding.node
  COPY Release/tree_sitter_java_binding.node
make: Leaving directory '/home/kamado/Documents/github/kamadorueda/tree-sitter-java/build'
```
`$ npm run-script test`

```
> tree-sitter-java@0.19.1 test /home/kamado/Documents/github/kamadorueda/tree-sitter-java
> tree-sitter test && script/parse-examples

  types:
    ✓ integral types
    ✓ floating point types
  comments:
    ✓ comment
    ✓ comments and literals
  declarations:
    ✓ local variable
    ✓ local array variable
    ✓ module
    ✓ module with normal annotation
    ✓ module with marker annotation
    ✓ module with single element annotation
    ✓ package_declaration
    ✓ module directive
    ✓ module directive with requires, exports, opens, uses and provides
    ✓ single type import declaration
    ✓ type_import_on_declaraction
    ✓ single static import declaration
    ✓ static import on demand declaration
    ✓ class declaration
    ✓ class declaration involving public, private, abstract and superclass
    ✓ class declaration with implements
    ✓ class declaration with body
    ✓ interface declaration
    ✓ interface declaration with extends
    ✓ interface with annotation type declaration
    ✓ method declaration
    ✓ constructor declaration
    ✓ throws
    ✓ object instantiation
    ✓ variable declaration
    ✓ enum declaration
    ✓ class declaration with dollar-sign identifiers
  precedence:
    ✓ Precedence
  expressions:
    ✓ standalone assignment expression
    ✓ standalone binary expression
    ✓ instanceof expressions
    ✓ if statements
    ✓ if statements with braces
    ✓ if statements with assignment without braces
    ✓ if then else statement
    ✓ nested if then else statements
    ✓ ternary expressions
    ✓ for statement
    ✓ Enhanced for statements
    ✓ while statement
    ✓ try-with-resources statements
    ✓ return statement
    ✓ annotation
    ✓ marker annotation
    ✓ single element annotation
    ✓ lambda expression
    ✓ switch statement
    ✓ type arguments
    ✓ wildcard
    ✓ type arguments with generic types
    ✓ empty type arguments
    ✓ method references
    ✓ Non-ascii identifiers
  literals:
    ✓ decimal integer literals
    ✓ hex integer literals
    ✓ octal integer literals
    ✓ binary integer literal
    ✓ floating point literals
    ✓ boolean literals
    ✓ character literals
    ✓ string literals
    ✓ null literals
    ✓ char escapes
    ✓ octal escapes
    ✓ unicode escapes
    ✓ ascii escapes
syntax highlighting:
  ✓ types.java (15 assertions)
Successfully parsed 10423 of 10423 example files (100.0%)
```

**Comment by kamadorueda** [comment]
Can we (the users) help the project in some way so PR like these can get merged or closed-with-a-comment? 

If the project needs maintainers I can volunteer myself

**Comment by aryx** [comment]
+1 to what @kamadorueda said.

**Comment by maxbrunsfeld** [comment]
@patrickt We might need some more tweaks like https://github.com/tree-sitter/tree-sitter-php/commit/c0e8713a8d87ed810adea20f9aef4b95c9df6b13 on other repositories to make sure that CI runs for PRs. I would have expected that that the existing `on: {push: branches: '**'}}` would work fine, but apparently we're not getting CI runs for PRs on this repo.

**Comment by aryx** [comment]
@kamadorueda I spoke with @dcreager and @maxbrunsfeld and they are opened to add more people with merge rights in the different tree-sitter-xxx languages. Hopefully this can accelerate things.

**Comment by aryx** [comment]
@patrickt any news on turning on CI for external contributors for this repository?
@dcreager could we get the commit/merging rights on this repository so we could merge this useful PR?

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
@dcreager @patrickt @maxbrunsfeld I approved the PR (thx to douglas merging rights), but still can't merge it. What do we need to do to get the tests to run? I clicked on the Checks tab, but I can't even re-run all jobs. Do I need to resubmit this PR as me so github accepts to run the CI because I'm part of the tree-sitter org?

**Comment by aryx** [comment]
Note that I did a test PR here: https://github.com/tree-sitter/tree-sitter-java/pull/74 and even though this time the github actions are running, the other CI are not and my PR is also blocked. @patrickt @dcreager @maxbrunsfeld can we remove those appveyer and travis-ci CI actions which do not seem to work and block the PRs?

**Pull request merged**
