### PR TITLE
Emma's switch changes

### PR DESCRIPTION
**Pull request by aryx**

### CODE REVIEW

**Comment by aryx** [comment]
This is a copy of https://github.com/tree-sitter/tree-sitter-java/pull/78 but from my account so we can get the CI correctly running (we need to fix that).

**Comment by maxbrunsfeld** [comment]
CI looks like it's running ok on https://github.com/tree-sitter/tree-sitter-java/pull/78.

**Comment by aryx** [comment]
yes because I made this PR. without this PR, it does not run on the other :) I don't fully understand why this PR unblock the CI in the other PR (github detects they are equivalent, I don't know), but it works.

**Comment by aryx** [comment]
We need to fix the CI like nathan did in tree-sitter-typescript for tree-sitter-java, so that we don't have to do this hack.

**Pull request merged**
