### PR TITLE
Add reserved unused keywords

### PR DESCRIPTION
**Pull request by sadikovi**
This PR adds support for reserved unused keywords (literals). Currently there are only two: `const` and `goto`.

The change allows highlighting of such keywords in an Atom grammar. Otherwise, it is difficult to highlight literals using regex, since the scope could be different, e.g. we should not highlight them in the comments.

### CODE REVIEW

**Comment by sadikovi** [comment]
@maxbrunsfeld can you review? Thanks.

**Comment by sadikovi** [comment]
Can I get a review on this PR?

**Comment by patrickt** [comment]
The grammars look good here, but generally we keep the Node binding information in a `bindings/node` subdirectory (since now there can be both Node and Rust bindings). Would you mind moving them?

**Comment by sadikovi** [comment]
@maxbrunsfeld Having a regex on identifier for const does not seem to work in Atom.

**Comment by sadikovi** [comment]
The purpose is mentioned in the PR description by the way.

**Pull request closed without merging**
